# Run only staticcheck for now. Additional linters will be enabled one-by-one.
linters:
  disable-all: true
  enable:
    - staticcheck
    - testifylint
linters-settings:
  testifylint:
    enable-all: true
